version: "2.1"

services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: ssh-server
    hostname: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_NAME=test
      - USER_PASSWORD=test
    ports:
      - 2222:2222

  samba-server:
    image: dperson/samba
    container_name: samba-server
    hostname: smb-server
    command: -s "public;/share;yes;no;yes;all;none;all;test" -u "test;test"
    ports:
      - 139:139
      - 445:445
